// ❗ ключ = строка, которая приходит с бэка ОДИН В ОДИН

export const ATM_WARNINGS_RU = {
  "Safe door open": "Открыта сейфовая дверь",
  "Bunch note acceptor full": "Приёмник пачек банкнот заполнен",
  "Bunch note acceptor nearly full": "Приёмник пачек банкнот почти заполнен",
  "Bunch note acceptor warning": "Предупреждение приёмника пачек банкнот",
  "Cardreader full": "Картоприёмник заполнен",
  "Cardreader warning": "Предупреждение картоприёмника",
  "Depository warning level 1 issued": "Хранилище: предупреждение уровня 1",
  "Depository warning level 2 issued": "Хранилище: предупреждение уровня 2",
  "Reject bin nearly full": "Контейнер отказов почти заполнен",
  "Reject bin full": "Контейнер отказов заполнен",
  "Encrypting pin pad warning": "Предупреждение PIN-пада",
  "Journal printer warning level 1 issued": "Журнальный принтер: предупреждение уровня 1",
  "Journal printer warning level 2 issued": "Журнальный принтер: предупреждение уровня 2",
  "Journal printer warning level 3 issued": "Журнальный принтер: предупреждение уровня 3",
  "Key fault": "Ошибка ключа",
  "Low currency - cassette #1": "Мало наличных в кассете №1",
  "Low currency - cassette #2": "Мало наличных в кассете №2",
  "Low currency - cassette #3": "Мало наличных в кассете №3",
  "Low currency - cassette #4": "Мало наличных в кассете №4",
  "Low currency - cassette #5": "Мало наличных в кассете №5",
  "Low currency - cassette #6": "Мало наличных в кассете №6",
  "Low currency - cassette #7": "Мало наличных в кассете №7",
  "Low currency - cassette #8": "Мало наличных в кассете №8",
  "Presenter warning": "Предупреждение выдачи банкнот",
  "Denomination error": "Ошибка номинала",
  "Receipt printer warning level 1 issued": "Принтер чеков: предупреждение уровня 1",
  "Receipt printer warning level 2 issued": "Принтер чеков: предупреждение уровня 2",
  "Receipt printer warning level 3 issued": "Принтер чеков: предупреждение уровня 3",
  "Retract limit reached": "Достигнут лимит втягивания банкнот",
  "Self test failure": "Ошибка самотестирования",
  "Trap failure occured": "Сбой ловушки банкнот",
};

export const ATM_ERRORS_RU = {
  "Card reader/writer down": "Картридер неисправен",
  "Depository down": "Хранилище неисправно",
  "Dispenser down": "Диспенсер неисправен",
  "Encrypting pin pad disabled": "PIN-пад отключён",
  "Encryptor down": "Шифратор неисправен",
  "First bill dispenser down": "Первая кассета неисправна",
  "Second bill dispenser down": "Вторая кассета неисправна",
  "Third bill dispenser down": "Третья кассета неисправна",
  "Fourth bill dispenser down": "Четвёртая кассета неисправна",
  "Fifth bill dispenser down": "Пятая кассета неисправна",
  "Sixth bill dispenser down": "Шестая кассета неисправна",
  "Seventh bill dispenser down": "Седьмая кассета неисправна",
  "Eighth bill dispenser down": "Восьмая кассета неисправна",
  "Floppy disk down": "Дисковод неисправен",
  "ICC operations disabled": "Операции ICC отключены",
  "Journal printer down": "Журнальный принтер неисправен",
  "Presenter down": "Модуль выдачи неисправен",
  "Receipt printer down": "Принтер чеков неисправен",
  "Time of day clock down": "Системные часы неисправны",
  "Validation printer down": "Принтер валидации неисправен",
};
