server {
    # HTTPS configuration
    listen 443 ssl;
    http2 on;
    
    server_name daily.tajikistan.tj daily.activ24.tj 10.65.10.20;
    
    ssl_certificate /etc/letsencrypt/live/daily/activ24.tj.crt;
    ssl_certificate_key /etc/letsencrypt/live/daily/activ24.tj.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384';

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/abs/ {
        proxy_pass http://abs_service:5000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/atm/ {
        proxy_pass http://10.64.1.10/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/conversion {
        proxy_pass http://10.64.1.55:8180/cxf/conversion/v1/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/loans {
        proxy_pass http://10.64.1.55:8180/cxf/loans/v1/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/cards {
        proxy_pass http://10.64.1.55:8180/cxf/cards/v1/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# HTTP redirect to HTTPS with specific domain
server {
    listen 80;
    server_name 10.65.10.20 daily.activ24.tj;
    
    # Redirect to https://daily.tajikistan.tj
    return 301 https://daily.tajikistan.tj$request_uri;
}
