export const visaCards = [
  // { id: 0, name: "Нет" },
  { id: 1, name: "Visa Gold_ 1635.03_ резидент" },
  { id: 2, name: "Viza Gold_ 1635.03 _не резидент" },
  { id: 3, name: "Vita Inindy, 1635 04 резидент" },
  { id: 4, name: "Visa Infnty_ 1635.04 нерезидент" },
  { id: 5, name: "Visa Gold Salay (Зачисленню TJSL 1635.07 резидент" },
  { id: 6, name: "Visa Gold Salary [Зачисление TJSL 1635.07 нерезидент" },
  { id: 7, name: "Visa Gold Salary (barkL 1635.09 резидент" },
  { id: 8, name: "Visa Gold Salary (barkL 1635.09 нерезидент" },
  { id: 9, name: "Visa Infinity Salary (bank L1635.10 резидент" },
  { id: 10, name: "Vita Ininty Salary [bank L 1635. 10 ерезидент" },
  { id: 11, name: "Visa Butiness, 1635.11 резидент" },
  { id: 12, name: "Visa Businen_ 1635.11 нерезидент" },
  { id: 13, name: "1635.16 Visa Gold Noresident" },
  { id: 14, name: "1635.17 Visa Signature Legal" },
  { id: 15, name: "1635.18 Visa Signature Individual" },
  { id: 16, name: "1635.19 Visa Signature Nonetident" },
];

export const ncCards = [
  // { id: 0, name: "Нет" },
  { id: 1, name: "Korti milly 1637.01" },
  { id: 2, name: "Korti milly Salary, 1637.02" },
  { id: 3, name: "Korti milly 1637.01" },
  { id: 4, name: "Korti milly 1637.01" },
];

export const mcCards = [
  // { id: 0, name: "Нет" },
  { id: 1, name: "MC Standerd_1636,02 резидент" },
  { id: 2, name: "MC Standard 1636:02 нерезидент" },
  { id: 3, name: "MC Wedd_1636.03 резидент" },
  { id: 4, name: "MC Wodd_ 1636.03" },
  { id: 5, name: "MC Piatinum_1636.04 резидент" },
  { id: 6, name: "MC Platinum 1636.04 нерезидент" },
  { id: 7, name: "MC Unembossed_1636:15 резицент" },
  { id: 8, name: "MC Unembossed_1635 15 нерезидент" },
  { id: 9, name: "1636.20 MC Platinum Nontesident" },
  { id: 10, name: "1636.21 MC World Nonresident" },
  { id: 11, name: "1636.24 MC World Elite" },
];

export const docTypes = [
  { value: 0, label: "Тип документа" },
  { value: 2, label: "Паспорт Республики Таджикистан" },
  { value: 3, label: "Паспорт РФ (с серией)" },
  { value: 4, label: "Военный билет" },
  { value: 5, label: "Свидетельство о рождении" },
  { value: 6, label: "Паспорт РФ (без серии]" },
  { value: 7, label: "Загранпаспорт гражданина РФ" },
  { value: 8, label: "Паспорт СССР" },
  { value: 9, label: "Заграничный паспорт РТ" },
  { value: 10, label: "Служ. карт." },
  { value: 11, label: "Паспорт" },
  { value: 12, label: "Заграничный паспорт ин." },
  { value: 13, label: "Удостоверение" },
];
export const reginTypes = [
  { value: 0, label: "Тип региона" },
  { value: 1, label: "Автономная область" },
  { value: 2, label: "АВТОНОМНЫЙ ОКРУГ" },
  { value: 3, label: "Край" },
  { value: 4, label: "Oбласть" },
  { value: 5, label: "Республика" },
];
export const USTypes = [
  { value: 0, label: "Тип нас пункта" },
  { value: 1, label: "Город - г" },
  { value: 2, label: "Городское поселение - ГО" },
];

export const districtTypes = [
  { value: 0, label: "Тип района" },
  { value: 1, label: "Волость" },
  { value: 2, label: "Остров" },
  { value: 3, label: "Район" },
  { value: 4, label: "Сельский округ" },
  { value: 5, label: "Улус" },
];
export const streetTypes = [
  { value: 0, label: "Тип улицы" },
  { value: 1, label: "Аллея" },
  { value: 2, label: "Бульвар" },
  { value: 3, label: "Вал" },
  { value: 4, label: "Въезд" },
  { value: 5, label: "Дорога" },
  { value: 6, label: "Заесд" },
  { value: 7, label: "Канал" },
  { value: 8, label: "Кольцо" },
  { value: 9, label: "Линия" },
  { value: 10, label: "Набережная" },
  { value: 11, label: "Парк" },
  { value: 12, label: "Переезд" },
  { value: 13, label: "Переулок" },
  { value: 14, label: "Площадка" },
  { value: 15, label: "Площадь" },
  { value: 16, label: "Полустанок" },
  { value: 17, label: "Проезд" },
  { value: 18, label: "Просек" },
  { value: 19, label: "Проселок" },
  { value: 20, label: "Проспект" },
  { value: 21, label: "Проулок" },
  { value: 22, label: "Разъезд" },
  { value: 23, label: "Сад" },
  { value: 24, label: "Сквер" },
  { value: 25, label: "Спуск" },
  { value: 26, label: "Тракт" },
  { value: 27, label: "Тупик" },
  { value: 28, label: "HnuLa" },
  { value: 29, label: "Участок" },
  { value: 30, label: "Шоссе" },
];
export const status = [
  { value: 0, label: "Статус" },
  { value: 1, label: "Заявка принята" },
  { value: 2, label: "Заявка обработана" },
  { value: 3, label: "Карта открыта" },
  { value: 4, label: "Карта активирована" },
  { value: 5, label: "Недостоверные данные" },
  { value: 6, label: "Отказано в карте" },
];
export const applicationsList = [
  {
    id: 1,
    appNumber: "123232",
    status: "Новая",
    agent: "Мобильный банк",
    clientName: "Иванов Иван Иванович",
    card: "Visa Gold",
    delivery: "Душанбе, Пушкина 2 кв 23",
    phone: "79550559652",
    codeWord: "Зима",
    cardName: "Ivanov Ivan",
    gender: "Муж",
    resident: "Нет",
    document: "Заграничный паспорт РФ Р.ЭЗВХРХУ",
    inn: "29595992",
    address: "Россия города Москвы улицы Черноморская д. 64 из 84",
    currency: "Мультивалютный",
    accountNumber: "42584526458 564056",
    contract: "№19759945694 65",
    date: "10.02.2024",
    passportScans: "",
    signedDocsScans: "",
    revisionScans: "",
  },
  {
    id: 2,
    appNumber: "123232",
    status: "Новая",
    agent: "Мобильный банк",
    clientName: "Иванов Иван Иванович",
    card: "Visa Gold",
    delivery: "Душанбе, Пушкина 2 кв 23",
    phone: "79550559652",
    codeWord: "Зима",
    cardName: "Ivanov Ivan",
    gender: "Муж",
    resident: "Нет",
    document: "Заграничный паспорт РФ Р.ЭЗВХРХУ",
    inn: "29595992",
    address: "Россия города Москвы улицы Черноморская д. 64 из 84",
    currency: "Мультивалютный",
    accountNumber: "42584526458 564056",
    contract: "№19759945694 65",
    date: "10.02.2024",
    passportScans: "",
    signedDocsScans: "",
    revisionScans: "",
  },
  {
    id: 3,
    appNumber: "123232",
    status: "Новая",
    agent: "Мобильный банк",
    clientName: "Иванов Иван Иванович",
    card: "Visa Gold",
    delivery: "Душанбе, Пушкина 2 кв 23",
    phone: "79550559652",
    codeWord: "Зима",
    cardName: "Ivanov Ivan",
    gender: "Муж",
    resident: "Нет",
    document: "Заграничный паспорт РФ Р.ЭЗВХРХУ",
    inn: "29595992",
    address: "Россия города Москвы улицы Черноморская д. 64 из 84",
    currency: "Мультивалютный",
    accountNumber: "42584526458 564056",
    contract: "№19759945694 65",
    date: "10.02.2024",
    passportScans: "",
    signedDocsScans: "",
    revisionScans: "",
  },
];
export const tableDataDef = [
  {
    id: 1,
    applicationId: "1222/32",
    status: "Отправлено в банк: 10/22/2064",
    comment: "-",
    fullName: "Иванов Иван Иванович",
    phone: "79259259452",
    codeWord: "Зина",
    cardName: "Ivanov Ivan",
    gender: "Муж",
    resident: "Нет",
    document: "Загрязненный паспорт РФ Р-29392929",
    inn: "29393992",
    address: "Россия города Москвы улица Чертановская д.6-м в 8А",
    card: 'Vita Gold (привёр "СО„LT")',
    passportScans: "https://vkd.tj/uploads/posts/2024-07/7ddf3b5eef_54.webp",
    signedDocsScans: "",
    revisionScans: "",
  },
  {
    id: 2,
    applicationId: "1222/32",
    status: "Отправлено в банк: 10/22/2064",
    comment: "-",
    fullName: "Иванов Иван Иванович",
    phone: "79259259452",
    codeWord: "Зина",
    cardName: "Ivanov Ivan",
    gender: "Муж",
    resident: "Нет",
    document: "Загрязненный паспорт РФ Р-29392929",
    inn: "29393992",
    address: "Россия города Москвы улица Чертановская д.6-м в 8А",
    card: 'Vita Gold (привёр "СО„LT")',
    passportScans: "https://vkd.tj/uploads/posts/2024-07/7ddf3b5eef_54.webp",
    signedDocsScans: "",
    revisionScans: "",
  },
  {
    id: 3,
    applicationId: "1222/32",
    status: "Отправлено в банк: 10/22/2064",
    comment: "-",
    fullName: "Иванов Иван Иванович",
    phone: "79259259452",
    codeWord: "Зина",
    cardName: "Ivanov Ivan",
    gender: "Муж",
    resident: "Нет",
    document: "Загрязненный паспорт РФ Р-29392929",
    inn: "29393992",
    address: "Россия города Москвы улица Чертановская д.6-м в 8А",
    card: 'Vita Gold (привёр "СО„LT")',
    passportScans: "https://vkd.tj/uploads/posts/2024-07/7ddf3b5eef_54.webp",
    signedDocsScans: "",
    revisionScans: "",
  },
];
