// export const visaCards = [
//   { id: 1635.03, name: "Visa Gold" },
//   { id: 1635.07, name: "Visa Gold Salary (Зачисление TJS)" },
//   { id: 1635.09, name: "Visa Gold Salary (bark)" },
//   { id: 1635.11, name: "Visa Business" },
//   { id: 1635.13, name: "Visa Gold Salary (Зачисление USD, EUR)" },
//   { id: 1635.16, name: "Visa Gold Nonresident" },
//   { id: 1635.17, name: "Visa Signature Legal" },
//   { id: 1635.18, name: "Visa Signature Individual" },
//   { id: 1635.19, name: "Visa Signature Nonresident" },
//   { id: 1635.22, name: "Maxcyc Visa Business" },
//   { id: 1635.23, name: "Maxcyc Visa Signature Individual" },
//   { id: 1635.29, name: "Visa Signature Zero" },
// ];

// export const ncCards = [
//   { id: 1637.01, name: "Korti Milli Fast Card" },
//   { id: 1637.01, name: "Oson Korti Milli" },
//   { id: 1637.01, name: "Korti Milli" },
//   { id: 1637.02, name: "Korti Milli Salary" },
// ];

// export const mcCards = [
//   { id: 1636.02, name: "MC Standard" },
//   { id: 1636.03, name: "MC World" },
//   { id: 1636.04, name: "MC Platinum" },
//   { id: 1636.05, name: "MC Standart Salary (Зачисление USD, EUR)" },
//   {
//     id: 1636.06,
//     name: "MC Standart Salary Зарплатный проекты  (Зачисление TJS)",
//   },
//   {
//     id: 1636.07,
//     name: "MC World Salary Зарплатный проекты  (Зачисление TJS)",
//   },
//   { id: 1636.08, name: "MC Platinum Salary (Зачисление TJS)" },
//   { id: 1636.09, name: "MC World Salary (bank)" },
//   { id: 1636.1, name: "MC Standart Salary (bank)" },
//   { id: 1636.11, name: "MC Platinum Salary (bank)" },
//   {
//     id: 1636.12,
//     name: "MC Unembossed Salary Зарплатный проекты  (Зачисление TJS)",
//   },
//   { id: 1636.17, name: "MC Platinum Salary (Зачисление USD, EUR)" },
//   { id: 1636.18, name: "MC World salary" },
//   { id: 1636.19, name: "MC Unembossed Salary (Зачисление USD, EUR)" },
//   { id: 1636.2, name: "MC Platinum Nonresident" },
//   { id: 1636.21, name: "MC World Nonresident" },
//   { id: 1636.22, name: "MC Preferred individual" },
//   { id: 1636.23, name: "MC Business" },
//   { id: 1636.24, name: "MC World Elite" },
//   { id: 1636.25, name: "MC World Elite Nonresident" },
//   { id: 1636.26, name: "Elite salary" },
//   { id: 1636.27, name: "MC Business salary" },
//   { id: 1636.28, name: "MC WORLD ELITE" },
//   { id: 1636.31, name: "Maxcyc MC Business Personal" },
//   { id: 1636.32, name: "MC World Zero" },
// ];
export const transactionTypes = [
  // { value: "0", label: "Тип транзакции" },
  { value: "2", label: "Снятие" },
  { value: "1", label: "Пополнение" },
  { value: "3", label: "Параметры" },
  { value: "4", label: "Мусор" },
];

export const visaCards = [
  { id: 1635.11, name: "Visa Business" },
  { id: 1635.07, name: "Visa Gold Salary (Зачисление  TJS)" },
  { id: 1635.16, name: "Visa Gold Nonresident" },
  { id: 1635.03, name: "Visa Gold" },
  { id: 1635.09, name: "Visa Gold Salary (bank)" },
  { id: 1635.13, name: "Visa Gold Salary  (Зачисление  USD, EUR)" },
  { id: 1635.15, name: "Easy Visa" },
  { id: 1635.17, name: "Visa Signature Legal" },
  { id: 1635.18, name: "Visa Signature Individual" },
  { id: 1635.19, name: "Visa Signature Nonresident" },
  { id: 1635.22, name: "махсус Visa businnes" },
  { id: 1635.23, name: "махсус Visa Signature Individual" },
  { id: 1635.24, name: " Visa VIRTUAL" },
  { id: 1635.29, name: " Visa Signature ZERO" },
];

export const ncCards = [
  { id: 1637.01, name: "Korti Milli Fast Card" },
  { id: 1637.01, name: "Oson Korti Milli" },
  { id: 1637.01, name: "Korti Milli" },
  { id: 1637.02, name: "Korti Milli Salary" },
];

export const mcCards = [
  { id: 1636.11, name: "MC Platinum Salary (bank)" },
  { id: 1636.08, name: "MC Platinum Salary (Зачисление  TJS)" },
  { id: 1636.2, name: "MC Platinum Nonresident" },
  { id: 1636.04, name: "MC Platinum" },
  { id: 1636.17, name: "MC Platinum Salary  (Зачисление  USD, EUR)" },
  { id: 1636.03, name: "MC World" },
  { id: 1636.21, name: "MC World Nonresident" },
  { id: 1636.02, name: "MC Standard" },
  {
    id: 1636.06,
    name: "MC Standart Salary Зарплатные проекты  (Зачисление  TJS)",
  },
  { id: 1636.1, name: "MC Standart Salary (bank)" },
  { id: 1636.05, name: "MC Standart Salary (Зачисление  USD, EUR)" },
  { id: 1636.23, name: "MC Business" },
  {
    id: 1636.07,
    name: "MC WORLD Salary Зарплатные проекты  (Зачисление  TJS)",
  },
  { id: 1636.09, name: "MC WORLD Salary  (bank)" },
  {
    id: 1636.12,
    name: "MC UNEMBOSSED Salary Зарплатные проекты    (Зачисление  TJS)",
  },
  { id: 1636.18, name: "MC WORLD Salary   (Зачисление  USD, EUR)" },
  { id: 1636.19, name: "MC UNEMBOSSED Salary   (Зачисление  USD, EUR)" },
  { id: 1636.22, name: "MC PREFFERED INDIVIDUAL" },
  { id: 1636.24, name: "MC WORLD ELITE" },
  { id: 1636.25, name: "MC WORLD ELITE NONRESIDENT" },
  { id: 1636.26, name: "MC WORLD ELITE SALARY " },
  { id: 1636.27, name: "MC BUSINESS SALARY" },
  { id: 1636.28, name: "МАХСУС MC WORLD ELITE" },
  { id: 1636.3, name: " MC VIRTUAL" },
  { id: 1636.31, name: "МАХСУС MC BUSINESS PERSONAL" },
  { id: 1636.32, name: " MC WORLD ZERO" },
];

export const statusCredit = [
  { value: 1, label: "Статус кредита" },
  { value: 1, label: "Принято" },
  { value: 2, label: "Передано в обработку" },
  { value: 3, label: "Обработано" },
  { value: 4, label: "Отказано" },
  { value: 5, label: "Доработка" },
];

export const loanTypes = [
  { value: "Тип кредита", label: "Тип кредита" },
  { value: "ПОД ЗАЛОГ ЗОЛОТА", label: "ПОД ЗАЛОГ ЗОЛОТА" },
  { value: "ПОТРЕБИТЕЛЬСКИЙ КРЕДИТ", label: "ПОТРЕБИТЕЛЬСКИЙ КРЕДИТ" },
  { value: "АВТОКРЕДИТ", label: "АВТОКРЕДИТ" },
  { value: "ДЛЯ РАЗВИТИЯ ХОЗЯЙСТВА", label: "ДЛЯ РАЗВИТИЯ ХОЗЯЙСТВА" },
  { value: "ДЛЯ РАЗВИТИЯ БИЗНЕСА", label: "ДЛЯ РАЗВИТИЯ БИЗНЕСА" },
  { value: "ПОД ЗАЛОГ ДЕПОЗИТА", label: "ПОД ЗАЛОГ ДЕПОЗИТА" },
];

export const offis = [
  { value: "Отделение получения", label: "Отделение получения" },
  {
    value: "Филиал в г.Душанбе ул.Айни 42 блок 2 (Садбарг)",
    label: "Филиал в г.Душанбе ул.Айни 42 блок 2 (Садбарг)",
  },
  {
    value: "ЦБО в г.Душанбе  ул.Дилкушо 26/1 (Джал Джам)",
    label: "ЦБО в г.Душанбе  ул.Дилкушо 26/1 (Джал Джам)",
  },
  {
    value: "ЦБО в г.Душанбе  ул.Южно Обходная 3-А (Корвон 7-8 ворота",
    label: "ЦБО в г.Душанбе  ул.Южно Обходная 3-А (Корвон 7-8 ворота)",
  },
  {
    value: "Филиал в г.Худжанд п-кт Камоли Худжанди 166 (Нацбанк)",
    label: "Филиал в г.Худжанд п-кт Камоли Худжанди 166 (Нацбанк)",
  },
  {
    value: "ЦБО в г. Бустон (тц Саховат 2 этаж)",
    label: "ЦБО в г. Бустон (тц Саховат 2 этаж)",
  },
  {
    value: "ЦБО в г.Шахритуз ул. Сомони 326 (парк Тус)",
    label: "ЦБО в г.Шахритуз ул. Сомони 326 (парк Тус)",
  },
  {
    value: "Филиал в г. Турсунзода ул. Сомони 6 (Прокуратура)",
    label: "Филиал в г. Турсунзода ул. Сомони 6 (Прокуратура)",
  },
  {
    value: "Филиал в г. Вахдат ул. Борбад 1 (Почта)",
    label: "Филиал в г. Вахдат ул. Борбад 1 (Почта)",
  },
  {
    value: "ЦБО в г. Вахдат ул. Улугбек 45 (Ёкут 2000)",
    label: "ЦБО в г. Вахдат ул. Улугбек 45 (Ёкут 2000)",
  },
  {
    value: "ЦБО в г. Панджакент п-кт Рудаки 89 (Дарвозаи Бухоро)",
    label: "ЦБО в г. Панджакент п-кт Рудаки 89 (Дарвозаи Бухоро)",
  },
  {
    value: "Филиал в г. Бохтар ул Б.Гафурова 53/17 (Фаровон)",
    label: "Филиал в г. Бохтар ул Б.Гафурова 53/17 (Фаровон)",
  },
  {
    value: "Филиал в г. Куляб ул. Сангак Сафарова (Бахор)",
    label: "Филиал в г. Куляб ул. Сангак Сафарова (Бахор)",
  },
  {
    value: "ЦБО в г. Гиссар ул. Аловудинова (тц Авицена)",
    label: "ЦБО в г. Гиссар ул. Аловудинова (тц Авицена)",
  },
  {
    value: "ЦБО в г. Шахринав ул. Сомони 8",
    label: "ЦБО в г. Шахринав ул. Сомони 8",
  },
  {
    value: "ЦБО в г. Кубодиен ул. Сомони (центральный светофор)",
    label: "ЦБО в г. Кубодиен ул. Сомони (центральный светофор)",
  },
  {
    value: "ЦБО в г. Восеъ ул. Сомони 2 (Хукумат)",
    label: "ЦБО в г. Восеъ ул. Сомони 2 (Хукумат)",
  },
];

export const docTypes = [
  { value: 0, label: "Тип документа" },
  { value: 58, label: "Паспорт Республики Таджикистан" },
  { value: 59, label: "Паспорт РФ (с серией)" },
  { value: 60, label: "Военный билет" },
  { value: 61, label: "Свидетельство о рождении" },
  { value: 62, label: "Паспорт РФ (без серии]" },
  { value: 63, label: "Загранпаспорт гражданина РФ" },
  { value: 64, label: "Паспорт СССР" },
  { value: 65, label: "Заграничный паспорт РТ" },
  { value: 66, label: "Служ. карт." },
  { value: 67, label: "Паспорт" },
  { value: 68, label: "Заграничный паспорт ин." },
  { value: 69, label: "Удостоверение" },
];

export const reginTypes = [
  { value: 0, label: "Тип региона" },
  { value: 1, label: "Автономная область" },
  { value: 2, label: "АВТОНОМНЫЙ ОКРУГ" },
  { value: 3, label: "Край" },
  { value: 4, label: "Oбласть" },
  { value: 5, label: "Республика" },
];
export const USTypes = [
  { value: 0, label: "Тип нас пункта" },
  { value: 1, label: "Город - г" },
  { value: 2, label: "Городское поселение - ГО" },
];

export const districtTypes = [
  { value: 0, label: "Тип района" },
  { value: 1, label: "Волость" },
  { value: 2, label: "Остров" },
  { value: 3, label: "Район" },
  { value: 4, label: "Сельский округ" },
  { value: 5, label: "Улус" },
];
export const depositCurrency = [
  { value: 0, label: "Валюта депозита" },
  { value: 1, label: "TJS" },
  { value: 2, label: "USD" },
  { value: 3, label: "EUR" },
];
export const streetTypes = [
  { value: 0, label: "Тип улицы" },
  { value: 1, label: "Аллея" },
  { value: 2, label: "Бульвар" },
  { value: 3, label: "Вал" },
  { value: 4, label: "Въезд" },
  { value: 5, label: "Дорога" },
  { value: 6, label: "Заесд" },
  { value: 7, label: "Канал" },
  { value: 8, label: "Кольцо" },
  { value: 9, label: "Линия" },
  { value: 10, label: "Набережная" },
  { value: 11, label: "Парк" },
  { value: 12, label: "Переезд" },
  { value: 13, label: "Переулок" },
  { value: 14, label: "Площадка" },
  { value: 15, label: "Площадь" },
  { value: 16, label: "Полустанок" },
  { value: 17, label: "Проезд" },
  { value: 18, label: "Просек" },
  { value: 19, label: "Проселок" },
  { value: 20, label: "Проспект" },
  { value: 21, label: "Проулок" },
  { value: 22, label: "Разъезд" },
  { value: 23, label: "Сад" },
  { value: 24, label: "Сквер" },
  { value: 25, label: "Спуск" },
  { value: 26, label: "Тракт" },
  { value: 27, label: "Тупик" },
  { value: 28, label: "HnuLa" },
  { value: 29, label: "Участок" },
  { value: 30, label: "Шоссе" },
];
export const status = [
  { value: 1, label: "Статус" },
  { value: 1, label: "Заявка принята" },
  { value: 2, label: "Заявка обработана" },
  { value: 3, label: "Карта открыта" },
  { value: 4, label: "Карта активирована" },
  { value: 5, label: "Недостоверные данные" },
  { value: 6, label: "Отказано в карте" },
];
export const applicationsList = [
  {
    id: 1,
    appNumber: "123232",
    status: "Новая",
    agent: "Мобильный банк",
    clientName: "Иванов Иван Иванович",
    card: "Visa Gold",
    delivery: "Душанбе, Пушкина 2 кв 23",
    phone: "79550559652",
    codeWord: "Зима",
    cardName: "Ivanov Ivan",
    gender: "Муж",
    resident: "Нет",
    document: "Заграничный паспорт РФ Р.ЭЗВХРХУ",
    inn: "29595992",
    address: "Россия города Москвы улицы Черноморская д. 64 из 84",
    currency: "Мультивалютный",
    accountNumber: "42584526458 564056",
    contract: "№19759945694 65",
    date: "10.02.2024",
    passportScans: "",
    signedDocsScans: "",
    revisionScans: "",
  },
  {
    id: 2,
    appNumber: "123232",
    status: "Новая",
    agent: "Мобильный банк",
    clientName: "Иванов Иван Иванович",
    card: "Visa Gold",
    delivery: "Душанбе, Пушкина 2 кв 23",
    phone: "79550559652",
    codeWord: "Зима",
    cardName: "Ivanov Ivan",
    gender: "Муж",
    resident: "Нет",
    document: "Заграничный паспорт РФ Р.ЭЗВХРХУ",
    inn: "29595992",
    address: "Россия города Москвы улицы Черноморская д. 64 из 84",
    currency: "Мультивалютный",
    accountNumber: "42584526458 564056",
    contract: "№19759945694 65",
    date: "10.02.2024",
    passportScans: "",
    signedDocsScans: "",
    revisionScans: "",
  },
  {
    id: 3,
    appNumber: "123232",
    status: "Новая",
    agent: "Мобильный банк",
    clientName: "Иванов Иван Иванович",
    card: "Visa Gold",
    delivery: "Душанбе, Пушкина 2 кв 23",
    phone: "79550559652",
    codeWord: "Зима",
    cardName: "Ivanov Ivan",
    gender: "Муж",
    resident: "Нет",
    document: "Заграничный паспорт РФ Р.ЭЗВХРХУ",
    inn: "29595992",
    address: "Россия города Москвы улицы Черноморская д. 64 из 84",
    currency: "Мультивалютный",
    accountNumber: "42584526458 564056",
    contract: "№19759945694 65",
    date: "10.02.2024",
    passportScans: "",
    signedDocsScans: "",
    revisionScans: "",
  },
];
export const tableDataDef = [
  {
    id: 1,
    applicationId: "1222/32",
    status: "Отправлено в банк: 10/22/2064",
    comment: "-",
    fullName: "Иванов Иван Иванович",
    phone: "79259259452",
    codeWord: "Зина",
    cardName: "Ivanov Ivan",
    gender: "Муж",
    resident: "Нет",
    document: "Загрязненный паспорт РФ Р-29392929",
    inn: "29393992",
    address: "Россия города Москвы улица Чертановская д.6-м в 8А",
    card: 'Vita Gold (привёр "СО„LT")',
    passportScans: "https://vkd.tj/uploads/posts/2024-07/7ddf3b5eef_54.webp",
    signedDocsScans: "",
    revisionScans: "",
  },
  {
    id: 2,
    applicationId: "1222/32",
    status: "Отправлено в банк: 10/22/2064",
    comment: "-",
    fullName: "Иванов Иван Иванович",
    phone: "79259259452",
    codeWord: "Зина",
    cardName: "Ivanov Ivan",
    gender: "Муж",
    resident: "Нет",
    document: "Загрязненный паспорт РФ Р-29392929",
    inn: "29393992",
    address: "Россия города Москвы улица Чертановская д.6-м в 8А",
    card: 'Vita Gold (привёр "СО„LT")',
    passportScans: "https://vkd.tj/uploads/posts/2024-07/7ddf3b5eef_54.webp",
    signedDocsScans: "",
    revisionScans: "",
  },
  {
    id: 3,
    applicationId: "1222/32",
    status: "Отправлено в банк: 10/22/2064",
    comment: "-",
    fullName: "Иванов Иван Иванович",
    phone: "79259259452",
    codeWord: "Зина",
    cardName: "Ivanov Ivan",
    gender: "Муж",
    resident: "Нет",
    document: "Загрязненный паспорт РФ Р-29392929",
    inn: "29393992",
    address: "Россия города Москвы улица Чертановская д.6-м в 8А",
    card: 'Vita Gold (привёр "СО„LT")',
    passportScans: "https://vkd.tj/uploads/posts/2024-07/7ddf3b5eef_54.webp",
    signedDocsScans: "",
    revisionScans: "",
  },
];
export const idMargent = [
  {
    label: "ЧДММ ХИЗМАТРАСОНИИ КУМАКИ РАВОДИДИ ГЛОБАЛИИ ТОЧИКИСТОН",
    value: 16846,
  },
  { label: "Арзон Тичорат", value: 18516 },
  { label: "Болаззати Диёр", value: 18639 },
  { label: "ЧДММ ХАЛИМИ ОЛИМ (Citir Usta – Опера балет)", value: 15387 },
  { label: "ЧДММ ХАЛИМИ ОЛИМ (Citir Usta – Алфемо)", value: 15387 },
  { label: "ЧДММ ХАЛИМИ ОЛИМ (СZN Burak)", value: 15387 },
  { label: "СИ Абдусаломов Шахобиддин Салохиддинович", value: 18764 },
  { label: "СИ Асоев Баходур Давлатович", value: 18826 },
  { label: "СИ Чаборов Мансурчон Аликулович", value: 18907 },
  { label: "ЧДММ Шахри Обод", value: 18904 },
  { label: "CИ Ниёзов Бобочон Рахматуллоевич", value: 18933 },
  { label: "ИП Саидов Сирочиддин", value: 18934 },
  { label: "ИП Ниёззода Далери Рахматулло", value: 18966 },
  { label: "ИП Бурханова Дилноза", value: 18942 },
  { label: "СИ Бахромов Шахромчон Бахромович", value: 18925 },
  { label: "СИ Окилов Аламат Окилбекович", value: 16685 },
  { label: "ИП Абдиева Хуршеда Мирзоевна", value: 9271 },
  { label: "ҶДММ Бахор Тиб", value: 19042 },
  { label: "СИ Бозидов Замонидин Азимович (Аль-Манди)", value: 19056 },
  { label: "СИ Бозидов Замонидин Азимович (Etno Pub)", value: 19056 },
  { label: "СИ Бозидов Замонидин Азимович (ALAF)", value: 19056 },
  { label: "СИ Нуридинов Амирхамза Мухидинович", value: 13332 },
  { label: "СИ Хасанов Манучехр Хуршедович", value: 13005 },
  { label: "СИ Мамарачабов Аббосчон Пирназарович", value: 9194 },
  { label: "СИ Тошев Худобахт Муҳаммадович", value: 19094 },
  { label: "СИ Хамраева Мавлюда Нарзикуловна", value: 4325 },
  { label: "ИП Саифидинова Фируза Аслидиновна", value: 19224 },
  { label: "СИ Муродов Мумин Холназарович", value: 19378 },
  { label: "НАВРУЗОВ РУЗИМУХАММАД ПИРНАЗАРОВИЧ", value: 19552 },
  { label: "ТОШМАТОВА МАЛОХАТ АБДУЛЛОЕВНА", value: 19551 },
  { label: "Тошматова Мафтуна Коммунаровна", value: 19550 },
  { label: "ХУСАНОВ САЪДУЛЛО ТУЙМУРАТОВИЧ", value: 19553 },
  { label: "Зарипов Абдулазиз Абдусаторович", value: 19544 },
  { label: "ШАРИФОВ РАЧАБАЛИ АМОНОВИЧ", value: 19545 },
  { label: "Нормуродова Сумая Акбаровна", value: 19547 },
  { label: "ДАВЛАТЗОДА МЕХРБОНУИ ХАЙДАР", value: 19546 },
  { label: "Хайбуллоев Собир Насруллоевич", value: 19548 },
  { label: "Давлатова Зарина Юсуфовна", value: 19549 },
];

export const TYPE_SEARCH_CLIENT = [
  {
    label: "Поиск по Номеру телефона",
    value: "client/info?phoneNumber=",
    inputLabel: "Номер телефона",
  },
  {
    label: "Поиск по Номеру индекса",
    value: "client/info/client-index?clientIndex=",
    inputLabel: "Номер индекса",
  },
  {
    label: "По номеру счета",
    value: "/abs-search/name?lname=",
    inputLabel: "Номер счета",
  },
  { label: "Поиск по INN", value: "client/info/inn?inn=", inputLabel: "INN" },
  {
    label: "Поиск по id карты",
    value: "abs-search/account?acc=",
    inputLabel: "id карты",
  },
  {
    label: "Поиск по имени пользователя",
    value: "/abs-searchв/name?lname=",
    inputLabel: "Ведите имя и фамилию пользователя",
  },
  {
    label: "Поиск по последним 4 цифрам карты",
    value: "abs-search/last-four?last4=",
    inputLabel: "Ведите последним 4 цифрам карты",
  },
];

export const dataTrans = [
  { label: 463, value: 2 },
  { label: 477, value: 1 },
  { label: 479, value: 2 },
  { label: 487, value: 1 },
  { label: 488, value: 1 },
  { label: 490, value: 2 },
  { label: 493, value: 3 },
  { label: 508, value: 2 },
  { label: 509, value: 2 },
  { label: 510, value: 2 },
  { label: 515, value: 2 },
  { label: 530, value: 2 },
  { label: 533, value: 2 },
  { label: 536, value: 3 },
  { label: 554, value: 2 },
  { label: 565, value: 3 },
  { label: 578, value: 3 },
  { label: 579, value: 1 },
  { label: 591, value: 2 },
  { label: 618, value: 1 },
  { label: 644, value: 3 },
  { label: 659, value: 2 },
  { label: 667, value: 2 },
  { label: 668, value: 2 },
  { label: 669, value: 1 },
  { label: 670, value: 2 },
  { label: 671, value: 2 },
  { label: 677, value: 2 },
  { label: 678, value: 2 },
  { label: 680, value: 2 },
  { label: 681, value: 1 },
  { label: 682, value: 2 },
  { label: 683, value: 2 },
  { label: 687, value: 1 },
  { label: 688, value: 2 },
  { label: 689, value: 2 },
  { label: 691, value: 2 },
  { label: 698, value: 2 },
  { label: 700, value: 2 },
  { label: 702, value: 2 },
  { label: 703, value: 2 },
  { label: 704, value: 2 },
  { label: 705, value: 1 },
  { label: 706, value: 2 },
  { label: 707, value: 2 },
  { label: 711, value: 1 },
  { label: 712, value: 1 },
  { label: 736, value: 2 },
  { label: 737, value: 2 },
  { label: 738, value: 1 },
  { label: 739, value: 1 },
  { label: 749, value: 2 },
  { label: 750, value: 1 },
  { label: 751, value: 3 },
  { label: 751, value: 3 },
  { label: 756, value: 3 },
  { label: 756, value: 3 },
  { label: 757, value: 3 },
  { label: 758, value: 3 },
  { label: 759, value: 3 },
  { label: 760, value: 1 },
  { label: 767, value: 1 },
  { label: 768, value: 1 },
  { label: 770, value: 2 },
  { label: 771, value: 2 },
  { label: 774, value: 2 },
  { label: 775, value: 1 },
  { label: 776, value: 2 },
  { label: 777, value: 2 },
  { label: 781, value: 2 },
  { label: 782, value: 3 },
  { label: 785, value: 1 },
  { label: 789, value: 1 },
  { label: 797, value: 3 },
  { label: 798, value: 3 },
  { label: 813, value: 1 },
];
