import test from 'node:test';
import assert from 'node:assert/strict';
import {cardExpiry,creditStatus} from './customerProductDetails.js';
import {filterComplianceRequests,matchEntries} from './complianceRequestFilters.js';
import {compactSearchEndpoint,complianceClientFields} from './compactClientSearch.js';
import {customerDirectoryQuery} from './customerDirectoryQuery.js';
test('card ISO expiry',()=>assert.equal(cardExpiry({expirationDate:'2028-11-30T00:00:00'}),'30.11.2028'));
test('processing expiry has priority',()=>assert.equal(cardExpiry({details:{expiryDate:'202811'},expirationDate:'2020-01-01'}),'11.2028'));
test('missing expiry is not invented',()=>assert.equal(cardExpiry({}),'Не указан'));
test('credit status matches frontovik priority',()=>assert.equal(creditStatus({params:{statusName:'Погашен'},statusName:'Актуален'}),'Погашен'));
const rows=[{id:1,status:'pending',client_identifier:'001234567',compliance_score:0,created_at:'2026-09-16T21:00:00Z',best_match:JSON.stringify([{source:'DROPPERS_LIST',data:{org_name:'Банк Тест'}}])},{id:2,status:'approved',compliance_score:5}];
test('search nested match data',()=>assert.equal(filterComplianceRequests(rows,{search:'банк тест'}).length,1));
test('source filtering',()=>assert.deepEqual(filterComplianceRequests(rows,{source:'DROPPERS_LIST'}).map(x=>x.id),[1]));
test('score zero is not all',()=>assert.deepEqual(filterComplianceRequests(rows,{score:0}).map(x=>x.id),[1]));
test('status filtering',()=>assert.deepEqual(filterComplianceRequests(rows,{status:'approved'}).map(x=>x.id),[2]));
test('dates use Dushanbe not UTC',()=>assert.deepEqual(filterComplianceRequests(rows,{from:'2026-09-17',to:'2026-09-17'}).map(x=>x.id),[1]));
test('bad match JSON is safe',()=>assert.deepEqual(matchEntries('{'),[]));
test('phone search strips only country prefix',()=>assert.deepEqual(compactSearchEndpoint('client/info?phoneNumber=','+992 885036600','/abs','/atm'),{url:'/atm/services/clientcode.php?phone=885036600',atm:true}));
test('all frontovik search modes supported',()=>{for(const mode of ['byCardId','byAccount','byName','byLast4','client/info/inn?inn=','client/info/client-index?clientIndex=']) assert.ok(compactSearchEndpoint(mode,'test','/abs','/atm').url);});
test('name is URL encoded',()=>assert.ok(compactSearchEndpoint('byName','А & Б','/abs','/atm').url.includes('%26')));
test('identity retains leading zero and date',()=>assert.deepEqual(complianceClientFields({TaxIdentificationNumber:{Code:'001234567'},LongName:'Тест Клиент',BirthDate:'1990-01-02T00:00:00'}),{inn:'001234567',full_name:'Тест Клиент',birth_date:'1990-01-02'}));
test('unsupported or empty search rejected',()=>{assert.throws(()=>compactSearchEndpoint('bad','X','/abs','/atm'));assert.throws(()=>compactSearchEndpoint('byName','','/abs','/atm'));});
test('new filters serialize for list and reports',()=>{const query=customerDirectoryQuery({card_status:'Актуален',credit_status:'Погашен',state_code:'OPENED',card_expiry_from:'2026-01-01',card_expiry_to:'2027-01-01'});assert.equal(new URLSearchParams(query).get('card_status'),'Актуален');assert.equal(new URLSearchParams(query).get('card_expiry_to'),'2027-01-01');});
